name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨2点执行
  workflow_dispatch:      # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/aalansehaiyang/technology-talk.git
    
    - name: Fetch upstream
      run: git fetch upstream
    
    - name: Merge upstream
      run: |
        git checkout master
        git merge upstream/master
    
    - name: Fix Windows incompatible filenames
      run: |
        find . -name '*[<>:"|?*]*' -type f | while read file; do
          newname=$(echo "$file" | sed 's/[<>:"|?*]/_/g')
          if [ "$file" != "$newname" ]; then
            echo "重命名: $file -> $newname"
            git mv "$file" "$newname"
          fi
        done
    
    - name: Commit and push changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "Sync with upstream and fix Windows filenames - $(date)"
          git push origin master
        fi
